name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: yanmanatkerno
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Docker build
        run: docker build -t yanmanatkerno/github-poc:latest

      - name: Docker push
        run: docker push -t yanmanatkerno/github-poc:latest
