name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create text file
        run: echo "This is a test file" > test_file.txt

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-fancy-artifact
          path: test_file.txt

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: yanmanatkerno
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Jib
        run: ./gradlew jib

      - name: Save Docker
        run: |
          docker save -o github-poc.tar yanmanatkerno/github-poc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: github-poc.tar
